name: test
permissions:
  contents: read

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '**.md'

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: '.go-version'
    - name: test
      run: make test
  testacc:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        terraform:
        - 1.5.7
        - 1.4.7
        - 1.3.10
        - 0.12.31
    env:
      TERRAFORM_VERSION: ${{ matrix.terraform }}
    steps:
    - uses: actions/checkout@v4
    - name: docker build
      run: docker-compose build
    - name: start localstack
      run: |
        docker-compose up -d localstack
        docker-compose run --rm dockerize -wait tcp://localstack:4566 -timeout 60s
        docker-compose exec -T localstack /etc/localstack/init/wait_s3_bucket_exists.sh
    - name: terraform --version
      run: docker-compose run --rm tfmigrate terraform --version
    - name: testacc
      run: docker-compose run --rm tfmigrate make testacc
